{
 "title": "API Monitoring Dashboard",
 "tags": [
  "API",
  "Monitoring",
  "Latency",
  "RPS",
  "Error Rate"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "50th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "99th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(http_request_duration_seconds_bucket[1m]))"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])"
    }
   ]
  },
  {
   "title": "Error Rate (5xx Responses)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{code=~\"5.*\"}[1m])"
    }
   ]
  }
 ]
}