controller:
  kind: DaemonSet
  
  reportNodeInternalIp: true
  allowSnippetAnnotations: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    type: NodePort
    # Enable metrics
    
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        prometheus.io/path: "/metrics"