apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'userservice'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['userservice.default.svc:80']

      - job_name: 'ingress-nginx'
        metrics_path: /metrics
        static_configs:
          - targets: ['ingress-nginx-controller-metrics.ingress-nginx.svc:10254']
