apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userservice-monitor
spec:
  selector:
    matchLabels:
      app: userservice
  endpoints:
    - port: http
      interval: 15s
